services:
  - type: web
    name: tuma-api
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install --prefix apps/api --include=dev && npm run build --prefix apps/api
    startCommand: node apps/api/dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: LWS_BRIDGE_URL
        value: https://bridges.eldnet.tech/tuma-bridge.php
      - key: LWS_BRIDGE_SECRET
        value: 53252ddafb841d3defe44023c025d56cd308a6dca1776d3f
      - key: TRACKING_BASE_URL
        value: https://api.tuma.eldnet.tech/v1/track
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
